version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    commit-message:
      prefix: "chore"
    labels:
      - "priority: low"
      - "scope: dependency"
      - "status: new"
      - "type: chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    commit-message:
      prefix: "chore"
    labels:
      - "priority: low"
      - "scope: dependency"
      - "status: new"
      - "type: chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    commit-message:
      prefix: "chore"
    labels:
      - "priority: low"
      - "scope: dependency"
      - "status: new"
      - "type: chore"
