name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rustfmt:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      - name: Run rustfmt
        working-directory: backend
        run: cargo fmt --all -- --check
  clippy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-dev libgtk-3-dev librsvg2-dev libwebkit2gtk-4.0-dev patchelf
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      - name: Run clippy
        working-directory: backend
        run: cargo clippy -- -D warnings
  prettier:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          check-latest: true
          cache: "npm"
      - name: Install frontend dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier
  eslint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          check-latest: true
          cache: "npm"
      - name: Install frontend dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
  vitest:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          check-latest: true
          cache: "npm"
      - name: Install frontend dependencies
        run: npm ci
      - name: Run vitest
        run: npm run test
