name: Update flake inputs
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update-lockfile:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          commit-msg: "chore: update inputs"
          pr-title: "chore: update inputs"
          pr-labels: |
            priority: low
            scope: dependency
            status: new
            type: chore
