name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-dev libgtk-3-dev librsvg2-dev libwebkit2gtk-4.0-dev patchelf
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          check-latest: true
      - name: Install frontend dependencies
        run: npm ci
      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: Nothing ${{ steps.changelog_reader.outputs.version }}
          releaseBody: ${{ steps.changelog_reader.outputs.changes }}
